spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: expense-tracker

  main:
    allow-circular-reference: true

output:
  ansi:
    enabled:ALWAYS

server:
  port: 8080
  servlet:
    context-path: /